# frozen_string_literal: true

source 'https://rubygems.org'

%w[rspec rspec-core rspec-expectations rspec-mocks rspec-support].each do |lib|
  gem lib, git: "https://github.com/rspec/#{lib}.git", branch: 'main'
end

gem 'faker', git: 'https://github.com/faker-ruby/faker.git', branch: 'master'

gem 'solargraph', group: :development

gem 'rake'
